config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
  

  end

  resources :categories
  devise_for :admins
  root 'home#index'
  # root 'admins/products#index'
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    @search = params[:search]
    @products = Product.all
    @products = @products.search(@search) if @search.present?
    
  end
    # GET /products/1 or /products/1.json
  def show
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Product List</h1>
<body>

    <div class="flex-container " >



        
        <% @products.each do |product| %>
        
            <div class="card" style="width: 500px;">
                <div class="card-body">
                    <h5 class="card-title"><%=product.title%></h5>
                    <p class="card-text">Description : <%=product.description%></p>
                    <p class="card-text p-y-1">Stock : <%=product.stock%></p>
                    <td>
                        <% if product.primary_image.attached? %>

                            <%= image_tag product.primary_image , width: "300px" , height: "300px" %>

                        <% end %>
                    </td>
                    </br>
                    </br>
                    <td><%= link_to 'Show', admins_product_path(product) %></td>
                    
                </div>
            </div>
        <% end %>

    </div>

         
       

</body>