config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
  

  end

  resources :categories
  devise_for :admins
  root 'home#index'
  # root 'admins/products#index'
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates :stock, numericality: {greater_than_or_equal_to: 0}
    has_many :categories_products
    has_many :categories, through: :categories_products
    enum status: [:draft, :published, :archived]
    has_one_attached :primary_image
    has_many_attached :supporting_images
    # attr_accessor :remove_primary_image, :remove_supporting_images
    # after_save :purge_primary_image, if: :remove_primary_image
    # private def purge_primary_image
    #     return unless @remove_primary_image == '1'
    #     primary_image.purge_later
    # end

    # after_save :purge_supporting_images, if: :remove_supporting_images
    # private def purge_supporting_images
    #     return unless @remove_supporting_images == '1'
    #     supporting_images.purge_later
    # end







end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController 
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /products or /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv {send_data generate_csv(Product.all), file_name: 'products.csv'}
    end


  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admins_product_path(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: admins_product_path(@product)
      }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admins_product_path(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: admins_product_path(@product)
      }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create title: attr[0], description: attr[1], stock: attr[2]
    end
    redirect_to admins_products_path
  end
  
  def delete_image_attachment
    @space_image = ActiveStorage::Attachment.find(params[:id])
    @space_image.purge
    redirect_back(fallback_location: request.referer)
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :stock ,:status,:primary_image ,:remove_primary_image, :remove_supporting_images ,:supporting_images=>[] ,:category_ids=>[])
    end

    
    def generate_csv(products)
      products.map do |product|
        [product.title, product.description, product.stock, product.status, product.created_at.to_date, product.updated_at.to_date].join(',')
      end.join("\n")
    end
  

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /products or /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv {send_data generate_csv(Product.all), file_name: 'products.csv'}
    end


  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create title: attr[0], description: attr[1], stock: attr[2]
    end
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :stock ,:status ,:category_ids=>[])
    end

    
    def generate_csv(products)
      products.map do |product|
        [product.title, product.description, product.stock, product.status, product.created_at.to_date, product.updated_at.to_date].join(',')
      end.join("\n")
    end

  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.html.erb
<%= form_with(model:[:admins, product]) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title ,class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description ,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock ,class:"form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_select :category_ids, Category.order(:name), :id, :name, {}, class:"form-control", multiple: true    %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%=  form.select :status , Product.statuses.keys.map {|u| [u.titleize, u]}, {}, class:"form-control"%>
  </div>
  <p>
  <strong>Primary image</strong>
  <% if product.primary_image.attached? %>

  <%= image_tag product.primary_image , width: "300px" , height: "300px" %>

  <%= link_to 'Remove', delete_image_attachment_admins_product_url(product.primary_image.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>





<% end %>
  
</p>


<p>
  <strong>Supporting images</strong>
  <% if product.supporting_images.attached? %>
  <% product.supporting_images.each do |image| %>
   




 <%= image_tag image , width: "50px" , height: "50px" %>
 <%= link_to 'Remove', delete_image_attachment_admins_product_url(image.id),
 method: :delete,
 data: { confirm: 'Are you sure?' } %>

  <%end%>
  
<%end%>
</p>


  <div class="field">
  <%= form.label :primary_image %>
  <%=  form.file_field :primary_image %>
</div>

<div class="field">
<%= form.label :supporting_images %>
<%=  form.file_field :supporting_images , multiple: true %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admins_product_path(@product) %>
<%= link_to 'Back', admins_products_path%>

app/views/admins/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class = "table">
  <thead>
    <tr>
      <th scope="col">Primary Image</th>
      <th scope="col">Supporting Image</th>

      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Stock</th>
      <th scope="col">Categories</th>
      <th scope="col">Status</th>



    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
      <td>
      <% if product.primary_image.attached? %>

        <%= image_tag product.primary_image , width: "300px" , height: "300px" %>

      <% end %>
      </td>
      <td>

      <% if product.supporting_images.attached? %>
        <% product.supporting_images.each do |image| %>




       <%= image_tag image , width: "50px" , height: "50px" %>
        <%end%>
      <%end%>
      </td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td> <%= product.categories.map(&:name).join(',')         %></td>
        <td><%= product.status %></td>
        <td><%= link_to 'Show', admins_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admins_product_path(product) %></td>
        <td><%= link_to 'Destroy', admins_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admins_product_path %>

<%= link_to 'Download CSV File ', admins_products_path(format: :csv) %>





<%= form_tag admins_products_csv_upload_path , multipart: true  do  %>
  <% if admin_signed_in? %>

  <%= file_field_tag :csv_file  %>
  <%= submit_tag :submit  %>
  <% end %>


<% end %>

app/views/admins/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admins_products_path %>

app/views/admins/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @product.categories.map(&:name).join(',') %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<p>
  <strong>Primary image</strong>
  <% if @product.primary_image.attached? %>

  <%= image_tag @product.primary_image , width: "300px" , height: "300px" %>

<% end %>
  
</p>


<p>
  <strong>Supporting images</strong>
  <% if @product.supporting_images.attached? %>
  <% @product.supporting_images.each do |image| %>




 <%= image_tag image , width: "50px" , height: "50px" %>
  <%end%>
<%end%>
</p>



<%= link_to 'Edit', edit_admins_product_path(@product) %> |
<%= link_to 'Back', admins_products_path %>