config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
  

  end

  resources :categories
  devise_for :admins
  root 'home#index'
  # root 'admins/products#index'
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>




<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" %>


  <head>
    <title>Blog</title>



    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Shoppee</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if admin_signed_in? %>
                   <li><%= link_to(' Home ', root_path                   ) %></li>
                    <p>  &nbsp  &nbsp </p>

                    <li><%= link_to(' Admin home ', admins_products_path) %></li>
                    <p>  &nbsp  &nbsp </p>


                    <li><%= link_to(' My Account ', edit_admin_registration_path) %></li>
                    <p> &nbsp  &nbsp  </p>
                    <li><%= link_to(' Categories ', categories_path) %></li>
                    <p> &nbsp  &nbsp  </p>
                    <li><%= link_to " Sign out ", destroy_admin_session_path, :method => :delete %></li>
                <% else %>
                <li><%= link_to(' Home ', root_path                   ) %></li>
                    <p>  &nbsp  &nbsp </p>
                  <li><%= link_to('Admin home ', admins_products_path) %></li>
                  <p>  &nbsp  &nbsp </p>


                    <li><%= link_to(' Sign in ', new_admin_session_path) %></li>
                    <p>  &nbsp  &nbsp </p>
                    <li><%= link_to(' Sign up ', new_admin_registration_path) %></li>



                <% end %>
    </ul>
    
  </div>
</nav>
    <%= yield %>
    
    

  </body>
</html>